#SIMPLE LINEAR REGRESSION

In [89]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'X':[6,2,10,4,8,18,11,15,16,3],'Y':[9,11,5,8,7,2,9,5,5,20]})
df

X   Y
0   6   9
1   2  11
2  10   5
3   4   8
4   8   7
5  18   2
6  11   9
7  15   5
8  16   5
9   3  20

In [90]:
x_train=df.loc[:4,['X']]
print(x_train)
y_train=df.loc[:4,['Y']]
y_train=np.array(y_train)
y_train=y_train.flatten()
print('-----------')
print(y_train)

    X
0   6
1   2
2  10
3   4
4   8
-----------
[ 9 11  5  8  7]


In [91]:
x_test=df.loc[5:,['X']]
print(x_test)
y_test=df.loc[5:,['Y']]
y_test=np.array(y_test)
y_test=y_test.flatten()
print('-----------')
print(y_test)

    X
5  18
6  11
7  15
8  16
9   3
-----------
[ 2  9  5  5 20]


In [92]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [93]:
model.intercept_   #intercept

11.9

In [94]:
model.coef_   #slope

array([-0.65])

In [95]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
print('Mean Absolute Error: ',mae)
print('R2 Score: ',r2)
print('Root Mean Squared Error: ',rmse)

Mean Absolute Error:  4.49
R2 Score:  0.28230633802816896
Root Mean Squared Error:  5.341862970911928


In [96]:
model.predict([[20]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-1.1])

#MULTI LINEAR REGRESSION

In [97]:
from sklearn import datasets
dia_x,dia_y=datasets.load_diabetes(return_X_y=True)
print(dia_x.shape)
print(dia_y.shape)

(442, 10)
(442,)


In [98]:
from sklearn.model_selection import train_test_split
di_x_train,di_x_test,di_y_train,di_y_test=train_test_split(dia_x,dia_y,test_size=0.3,random_state=2)

In [99]:
model.fit(di_x_train,di_y_train)
print('Intercept: ',model.intercept_)
print('Coefficients: ',model.coef_)

Intercept:  152.6275795791894
Coefficients:  [ -31.80406415 -214.66452697  445.14791885  376.34786891 -802.50380919
  525.99207358  106.4287134   172.3171033   799.50335529   57.1646797 ]


In [100]:
di_y_pred=model.predict(di_x_test)
di_mae=mean_absolute_error(di_y_test,di_y_pred)
di_rmse=np.sqrt(mean_squared_error(di_y_test,di_y_pred))
di_r2=r2_score(di_y_test,di_y_pred)
print('Mean Absolute Error: ',di_mae)
print('Root Mean Squared Error: ',di_rmse)
print('R2 Score: ',di_r2)

Mean Absolute Error:  44.199315876914966
Root Mean Squared Error:  54.034950681329846
R2 Score:  0.5012577617513011


#SVR

In [101]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(di_x_train,di_y_train)
pre=svr.predict(di_x_test)
mae1=mean_absolute_error(di_y_test,pre)
rmse1=np.sqrt(mean_squared_error(di_y_test,pre))
r21=r2_score(di_y_test,pre)
print('Mean Absolute Error: ',mae1)
print('Root Mean Squared Error: ',rmse1)
print('R2 Score: ',r21)

Mean Absolute Error:  59.77965957843949
Root Mean Squared Error:  71.76999530758795
R2 Score:  0.1201422438039742


#KNN

In [102]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=3)
knn.fit(di_x_train,di_y_train)
pred=knn.predict(di_x_test)
mae3=mean_absolute_error(di_y_test,pred)
rmse3=np.sqrt(mean_squared_error(di_y_test,pred))
r3=r2_score(di_y_test,pred)
print('Mean Absolute Error: ',mae3)
print('Root Mean Squared Error: ',rmse3)
print('R2 Score: ',r3)

Mean Absolute Error:  52.03508771929825
Root Mean Squared Error:  67.16260396800246
R2 Score:  0.2294839619064224


In [103]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=7)
knn.fit(di_x_train,di_y_train)
pred1=knn.predict(di_x_test)
mae7=mean_absolute_error(di_y_test,pred1)
rmse7=np.sqrt(mean_squared_error(di_y_test,pred1))
r7=r2_score(di_y_test,pred1)
print('Mean Absolute Error: ',mae7)
print('Root Mean Squared Error: ',rmse7)
print('R2 Score: ',r7)

Mean Absolute Error:  50.21911922663803
Root Mean Squared Error:  62.65140384838714
R2 Score:  0.3295162683784897


# EG:- HOUSE PRICE


In [104]:
house=pd.read_csv('/content/house_price.csv')
house

Transaction date  House age  \
0    2012-09-02 16:42:30.519336       13.3   
1    2012-09-04 22:52:29.919544       35.5   
2    2012-09-05 01:10:52.349449        1.1   
3    2012-09-05 13:26:01.189083       22.2   
4    2012-09-06 08:29:47.910523        8.5   
..                          ...        ...   
409  2013-07-25 15:30:36.565239       18.3   
410  2013-07-26 17:16:34.019780       11.9   
411  2013-07-28 21:47:23.339050        0.0   
412  2013-07-29 13:33:29.405317       35.9   
413  2013-08-01 09:49:41.506402       12.0   

     Distance to the nearest MRT station  Number of convenience stores  \
0                             4082.01500                             8   
1                              274.01440                             2   
2                             1978.67100                            10   
3                             1055.06700                             5   
4                              967.40000                             6   
..                                   ...                           ...   
409                            170.12890                             6   
410                            323.69120                             2   
411                            451.64190                             8   
412                            292.99780                             5   
413                             90.45606                             6   

      Latitude   Longitude  House price of unit area  
0    25.007059  121.561694                  6.488673  
1    25.012148  121.546990                 24.970725  
2    25.003850  121.528336                 26.694267  
3    24.962887  121.482178                 38.091638  
4    25.011037  121.479946                 21.654710  
..         ...         ...                       ...  
409  24.981186  121.486798                 29.096310  
410  24.950070  121.483918                 33.871347  
411  24.963901  121.543387                 25.255105  
412  24.997863  121.558286                 25.285620  
413  24.952904  121.526395                 37.580554  

[414 rows x 7 columns]

In [105]:
hx=house.drop(['House price of unit area'],axis=1)
hy=house['House price of unit area']

In [106]:
from sklearn.model_selection import train_test_split
hx_train,hx_test,hy_train,hy_test=train_test_split(hx,hy,test_size=0.3,random_state=2)

In [107]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
all_dates = pd.concat([hx_train['Transaction date'], hx_test['Transaction date']]).astype(str)
le.fit(all_dates)
hx_train['Transaction date'] = le.transform(hx_train['Transaction date'].astype(str))
hx_test['Transaction date'] = le.transform(hx_test['Transaction date'].astype(str))

In [108]:
model.fit(hx_train,hy_train)
print('Intercept: ',model.intercept_)
print('Coefficients: ',model.coef_)

Intercept:  2077.6438180653186
Coefficients:  [ 6.39002491e-03 -1.01639821e-03 -8.76448803e-03  1.84255923e+00
  7.81008845e+01 -3.29085472e+01]


In [109]:
hy_pred=model.predict(hx_test)
h_mae=mean_absolute_error(hy_test,hy_pred)
h_rmse=np.sqrt(mean_squared_error(hy_test,hy_pred))
h_r2=r2_score(hy_test,hy_pred)
print('Mean Absolute Error: ',h_mae)
print('Root Mean Squared Error: ',h_rmse)
print('R2 Score: ',h_r2)

Mean Absolute Error:  9.565454672753281
Root Mean Squared Error:  11.216005578102623
R2 Score:  0.491958806925207


#compare avg metric value over 100 run


In [110]:
#MAE
h_mae1=[]
for i in range(1,101):
  x1_train,x1_test,y1_train,y1_test=train_test_split(hx,hy,test_size=0.3,random_state=i)
  from sklearn.preprocessing import LabelEncoder
  le=LabelEncoder()
  all_dates = pd.concat([x1_train['Transaction date'], x1_test['Transaction date']]).astype(str)
  le.fit(all_dates)
  x1_train['Transaction date'] = le.transform(x1_train['Transaction date'].astype(str))
  x1_test['Transaction date'] = le.transform(x1_test['Transaction date'].astype(str))
  model.fit(x1_train,y1_train)
  y1_pred=model.predict(x1_test)
  h_mae=mean_absolute_error(y1_test,y1_pred)
  h_mae1.append(h_mae)
avg_mae=sum(h_mae1)/len(h_mae1)
print('Avg Mean Absolute Error: ',avg_mae)

Avg Mean Absolute Error:  9.4114245589242


In [111]:
#RMSE
h_rmse1=[]
for i in range(1,101):
  x1_train,x1_test,y1_train,y1_test=train_test_split(hx,hy,test_size=0.3,random_state=i)
  from sklearn.preprocessing import LabelEncoder
  le=LabelEncoder()
  all_dates = pd.concat([x1_train['Transaction date'], x1_test['Transaction date']]).astype(str)
  le.fit(all_dates)
  x1_train['Transaction date'] = le.transform(x1_train['Transaction date'].astype(str))
  x1_test['Transaction date'] = le.transform(x1_test['Transaction date'].astype(str))
  model.fit(x1_train,y1_train)
  y1_pred=model.predict(x1_test)
  h_rmse=np.sqrt(mean_squared_error(y1_test,y1_pred))
  h_rmse1.append(h_rmse)
avg_rmse=sum(h_rmse1)/len(h_rmse1)
print('Root Mean Square Error: ',avg_rmse)

Root Mean Square Error:  11.078924769971614


In [112]:
#R2 SCORE
h_R2_SC=[]
for i in range(1,101):
  x1_train,x1_test,y1_train,y1_test=train_test_split(hx,hy,test_size=0.3,random_state=i)
  from sklearn.preprocessing import LabelEncoder
  le=LabelEncoder()
  all_dates = pd.concat([x1_train['Transaction date'], x1_test['Transaction date']]).astype(str)
  le.fit(all_dates)
  x1_train['Transaction date'] = le.transform(x1_train['Transaction date'].astype(str))
  x1_test['Transaction date'] = le.transform(x1_test['Transaction date'].astype(str))
  model.fit(x1_train,y1_train)
  y1_pred=model.predict(x1_test)
  h_R2=r2_score(y1_test,y1_pred)
  h_R2_SC.append(h_R2)
avg_R2_SC=sum(h_R2_SC)/len(h_R2_SC)
print('R2 Score: ',avg_R2_SC)

R2 Score:  0.5008177416060906
