#IMPORTING LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

#NUMERICAL (PEARSONS CORRELATION)

In [ ]:
df1 = pd.DataFrame({'RollNo': [1, 2, 3, 4, 5],
                   'Mark1': [48,35,17,23,47],
                   'Mark2': [45,20,40,25,45]})
df1

RollNo  Mark1  Mark2
0       1     48     45
1       2     35     20
2       3     17     40
3       4     23     25
4       5     47     45

In [ ]:
corr,_= pearsonr(df1['Mark1'],df1['Mark2'])
print('Pearsons correlation:',corr)

Pearsons correlation: 0.42859374244583887


In [ ]:
corr,_= pearsonr(df1['Mark1'],df1['Mark1'])
print('Pearsons correlation:',corr)

Pearsons correlation: 1.0


#CATEGORICAL (CHI-SQUARE CORRELATION)


In [ ]:
df = pd.DataFrame({'Order': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                            11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                   'Product': ['TV', 'TV', 'Comp', 'TV', 'TV', 'Comp',
                               'Comp', 'Comp', 'TV', 'Radio', 'TV', 'Radio', 'Radio',
                               'Radio', 'Comp', 'Comp', 'TV', 'TV', 'Radio', 'TV'],
                   'State': ['Odisha', 'Odisha', 'Odisha', 'Odisha', 'Bihar', 'Bihar', 'Bihar', 'Bihar', 'Bihar', 'Bihar', 'Bihar',
                               'Bihar', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh', 'Chattisgarh']})

In [ ]:
df

Order Product        State
0       1      TV       Odisha
1       2      TV       Odisha
2       3    Comp       Odisha
3       4      TV       Odisha
4       5      TV        Bihar
5       6    Comp        Bihar
6       7    Comp        Bihar
7       8    Comp        Bihar
8       9      TV        Bihar
9      10   Radio        Bihar
10     11      TV        Bihar
11     12   Radio        Bihar
12     13   Radio  Chattisgarh
13     14   Radio  Chattisgarh
14     15    Comp  Chattisgarh
15     16    Comp  Chattisgarh
16     17      TV  Chattisgarh
17     18      TV  Chattisgarh
18     19   Radio  Chattisgarh
19     20      TV  Chattisgarh

In [ ]:
df.shape

(20, 3)

In [ ]:
ct=pd.crosstab(index=df['State'],columns=df['Product'],margins=True)
ct

Product      Comp  Radio  TV  All
State                            
Bihar           3      2   3    8
Chattisgarh     2      3   3    8
Odisha          1      0   3    4
All             6      5   9   20

In [ ]:
ar_df=np.array(ct)
ar_df

array([[ 3,  2,  3,  8],
       [ 2,  3,  3,  8],
       [ 1,  0,  3,  4],
       [ 6,  5,  9, 20]])

In [ ]:
ex_tab=np.zeros([3,3])
ex_tab

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
for i in range(3):
  for j in range(3):
    ex_tab[i,j]=(ar_df[i,3]*ar_df[3,j])/ar_df[3,3]
ex_tab

array([[2.4, 2. , 3.6],
       [2.4, 2. , 3.6],
       [1.2, 1. , 1.8]])

In [ ]:
ct1=ar_df[:3,:3]
ct1

array([[3, 2, 3],
       [2, 3, 3],
       [1, 0, 3]])

In [ ]:
t=(ct1-ex_tab)**2/ex_tab
t

array([[0.15      , 0.        , 0.1       ],
       [0.06666667, 0.5       , 0.1       ],
       [0.03333333, 1.        , 0.8       ]])

In [ ]:
sum(t)

array([0.25, 1.5 , 1.  ])

In [ ]:
sum(sum(t))
#accepted with 0.975 probability

2.75

#HEART DISEASE

In [ ]:
data=pd.read_csv('/content/H_DDataset.csv')

In [ ]:
data

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
...   ...  ...              ...           ...          ...   
1185   45    1                1           110          264   
1186   68    1                4           144          193   
1187   57    1                4           130          131   
1188   57    0                2           130          236   
1189   38    1                3           138          175   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0             172                0   
1                       0            0             156                0   
2                       0            1              98                0   
3                       0            0             108                1   
4                       0            0             122                0   
...                   ...          ...             ...              ...   
1185                    0            0             132                0   
1186                    1            0             141                0   
1187                    0            0             115                1   
1188                    0            2             174                0   
1189                    0            0             173                0   

      oldpeak  ST slope  target  
0         0.0         1       0  
1         1.0         2       1  
2         0.0         1       0  
3         1.5         2       1  
4         0.0         1       0  
...       ...       ...     ...  
1185      1.2         2       1  
1186      3.4         2       1  
1187      1.2         2       1  
1188      0.0         2       1  
1189      0.0         1       0  

[1190 rows x 12 columns]

In [ ]:
#CORRELATION BETWEEN MAX HERAT RATE AND RESTING BPS
corr,_=pearsonr(data['max heart rate'],data['resting bp s'])
print('Pearsons correlation:',corr)

Pearsons correlation: -0.1013569010590402


In [ ]:
#CORRELATION BETWEEN CHEST PAIN AND FASTING BLOOD SUGAR
data['chest pain type']=data['chest pain type'].astype(str)
data['fasting blood sugar']=data['fasting blood sugar'].astype(str)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1190 entries, 0 to 1189
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  1190 non-null   int64  
 1   sex                  1190 non-null   int64  
 2   chest pain type      1190 non-null   object 
 3   resting bp s         1190 non-null   int64  
 4   cholesterol          1190 non-null   int64  
 5   fasting blood sugar  1190 non-null   object 
 6   resting ecg          1190 non-null   int64  
 7   max heart rate       1190 non-null   int64  
 8   exercise angina      1190 non-null   int64  
 9   oldpeak              1190 non-null   float64
 10  ST slope             1190 non-null   int64  
 11  target               1190 non-null   int64  
dtypes: float64(1), int64(9), object(2)
memory usage: 111.7+ KB


In [ ]:
cont_tab=pd.crosstab(index=data['chest pain type'],columns=data['fasting blood sugar'],margins=True)
cont_tab

fasting blood sugar    0    1   All
chest pain type                    
1                     48   18    66
2                    192   24   216
3                    225   58   283
4                    471  154   625
All                  936  254  1190

In [ ]:
ob_val_tab=np.asarray(cont_tab)
ob_val_tab

array([[  48,   18,   66],
       [ 192,   24,  216],
       [ 225,   58,  283],
       [ 471,  154,  625],
       [ 936,  254, 1190]])

In [ ]:
exp_val=np.zeros([4,2])
exp_val

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ob_val=ob_val_tab[:4,:2]
ob_val

array([[ 48,  18],
       [192,  24],
       [225,  58],
       [471, 154]])

In [ ]:
for i in range(4):
  for j in range(2):
    exp_val[i,j]=(ob_val_tab[i,2]*ob_val_tab[4,j])/ob_val_tab[4,2]
exp_val

array([[ 51.91260504,  14.08739496],
       [169.89579832,  46.10420168],
       [222.59495798,  60.40504202],
       [491.59663866, 133.40336134]])

In [ ]:
t1=(ob_val-exp_val)**2/exp_val
t1

array([[ 0.29488942,  1.08667914],
       [ 2.8758553 , 10.59764   ],
       [ 0.02598544,  0.09575736],
       [ 0.86294635,  3.17999127]])

In [ ]:
sum(sum(t1))

19.019744268645525